[proxmox_nodes]
pve-master ansible_host=10.5.0.10

[management_vms]
mgmt-jump-01 ansible_host=10.5.0.20

[docker_hosts]
docker-prod-01 ansible_host=10.5.0.30

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
